// List constants
export const GET_USER_LIST = 'GET_USER_LIST';
export const POST_ITEM_TO_LIST = 'POST_ITEM_TO_LIST';
export const PUT_CHANGE_ITEM_ON_LIST = 'PUT_CHANGE_ITEM_ON_LIST';
export const DELETE_ITEM_FROM_LIST = 'DELETE_ITEM_FROM_LIST';

export const CHANGE_LIST_TO_DISPLAY = 'CHANGE_LIST_TO_DISPLAY';