// Navbar constants
export const NAVBAR_NEW_ENTRY = 'NAVBAR_NEW_ENTRY';
export const NAVBAR_BACK = 'NAVBAR_BACK';
export const UPDATE_TOAST_INFO = 'UPDATE_TOAST_INFO';
export const CHANGE_PAGE_TO_DISPLAY = 'CHANGE_PAGE_TO_DISPLAY';