// Player data constants
export const PLAYER_GET_PLAYER_LIST = 'PLAYER_GET_PLAYER_LIST';
export const PLAYER_POST_NEW_PLAYER = 'PLAYER_POST_NEW_PLAYER';
export const PLAYER_DELETE_NEW_PLAYER = 'PLAYER_DELETE_NEW_PLAYER';