// Tourney data constants
export const TOURNEY_GET_TOURNEY_LIST = 'TOURNEY_GET_TOURNEY_LIST';
export const TOURNEY_GET_TOURNEY_DETAILS = 'TOURNEY_GET_TOURNEY_DETAILS';
export const TOURNEY_RESET_TOURNEY_DETAILS = 'TOURNEY_RESET_TOURNEY_DETAILS';
export const TOURNEY_POST_NEW_TOURNEY = 'TOURNEY_POST_NEW_TOURNEY';
export const TOURNEY_PUT_TOURNEY = 'TOURNEY_PUT_TOURNEY';
export const TOURNEY_PUT_TOURNEY_DETAILS = 'TOURNEY_PUT_TOURNEY_DETAILS';
export const TOURNEY_DELETE_NEW_TOURNEY = 'TOURNEY_DELETE_NEW_TOURNEY';
